
fullnameOverride: "exercises"

replicaCount: 3

service:
  port: 4525
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4525"

volumes:
  - name: exercises-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"

containers:
  - name: exercises
    image: cyberdojo/exercises-start-points
    securityContext:
      runAsUser: 65534 # nobody
      fsGroup: 65534 # nobody
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: exercises-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
    livenessProbe:
      path: /alive?
      port: 4525
    readinessProbe:
      path: /ready?
      port: 4525

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
